/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package displays.Function1Manager;

import controllers.Function1.CapNhatController;
import controllers.Function1.HoKhauController;
import controllers.Function1.HoKhau_InfoController;
import controllers.Function1.KhaiTuController;
import displays.MainFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.HoKhauModel;
import models.NhanKhauModel;
import models.ThayDoiHKModel;
import utilities.MysqlConnection;

/**
 *
 * @author Loc Nguyen
 */
public class NhanKhau_KhaiTu extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoi
     */
    HoKhauController hkController = new HoKhauController();
    CapNhatController cnController = new CapNhatController();
    KhaiTuController ktController = new KhaiTuController();
    HoKhauModel hoKhau = new HoKhauModel();
    NhanKhauModel ngKhai = new NhanKhauModel();
    NhanKhauModel ngMat = new NhanKhauModel();

    private boolean check1 = false; //check xem nhan nut 'kiem tra' chua
    private boolean check2 = false;

    public NhanKhau_KhaiTu() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng?", "Warning!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
        });
    }

    private void close() {
        MainFrame.it.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKiemTraNgMat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtHoTenNgMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoiThuongTru = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        txtCmndNgMat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        dateNgayMat = new com.toedter.calendar.JDateChooser();
        btnKiemTraNgKhai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHoTenNgKhai = new javax.swing.JTextField();
        txtCmndNgKhai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSđt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khai tử");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khai tử");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Số CMT/CCCD người mất:");

        btnKiemTraNgMat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKiemTraNgMat.setText("Kiểm tra");
        btnKiemTraNgMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraNgMatActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Họ và tên người mất:");

        txtHoTenNgMat.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ngày sinh người mất:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nơi thường trú người mất:");

        txtQuocTich.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Giới tính người mất:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Quốc tịch người mất:");

        txtNoiThuongTru.setEditable(false);

        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Ngày mất:");

        txtGioiTinh.setEditable(false);

        btnKiemTraNgKhai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKiemTraNgKhai.setText("Kiểm tra");
        btnKiemTraNgKhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraNgKhaiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Họ và tên người khai:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Số CMT/CCCD người khai:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Nếu người mất không có người thân thì Số CMT/CCCD người khai điền là admin");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("SĐT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateNgayMat, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHoTenNgMat)
                                            .addComponent(txtQuocTich)
                                            .addComponent(txtNoiThuongTru)
                                            .addComponent(txtCmndNgMat, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXacNhan)
                                    .addComponent(btnKiemTraNgMat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtHoTenNgKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSđt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCmndNgKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnKiemTraNgKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCmndNgKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnKiemTraNgKhai, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTenNgKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSđt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKiemTraNgMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCmndNgMat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTenNgMat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNgayMat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKiemTraNgMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraNgMatActionPerformed
        if (txtCmndNgMat.getText().trim().length() != 8
                && txtCmndNgMat.getText().trim().length() != 9
                && txtCmndNgMat.getText().trim().length() != 12) {
            check2 = false;
            JOptionPane.showMessageDialog(rootPane, "Định dạng số CMT/CCCD không hợp lệ!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (txtCmndNgMat.getText().trim().equals(txtCmndNgKhai.getText().trim())) {
            JOptionPane.showMessageDialog(rootPane, "Số CMT/CCCD của người khai và người mất phải khác nhau!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (ktController.checkCmndSs_Cn(txtCmndNgMat.getText().trim())) {
            check2 = false;
            JOptionPane.showMessageDialog(rootPane, "Số CMT/CCCD chưa có trong hệ thống!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            HoKhau_Info hkInfo = new HoKhau_Info();
            int countMember = 0;
            if (!hkController.findByCondition(txtCmndNgMat.getText().trim()).isEmpty()) {
                hoKhau = hkController.findByCondition(txtCmndNgMat.getText().trim()).get(0);
                hkInfo.hoKhau = hoKhau;
                countMember = hkInfo.findMember().size();
            } else {
                hoKhau = null;
            }
            if (hoKhau == null || countMember <= 1) {
                check2 = true;
                JOptionPane.showMessageDialog(rootPane, "Kiểm tra thành công!");

                ngMat = ktController.findByCondition(txtCmndNgMat.getText().trim()).get(0);
                txtHoTenNgMat.setText(ngMat.getHoTen());
                dateNgaySinh.setDate(ngMat.getNgaySinh());
                txtGioiTinh.setText(ngMat.getGioiTinh());
                txtQuocTich.setText(ngMat.getQuocTich());
                txtNoiThuongTru.setText(ngMat.getDcHienNay());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Người này là chủ hộ " + hoKhau.getMaHoKhau()
                        + " và hộ này có nhiều hơn 1 thành viên. Bạn cần đổi chủ hộ trước!", "Warning!", JOptionPane.WARNING_MESSAGE);
                check2 = false;
            }
        }
    }//GEN-LAST:event_btnKiemTraNgMatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng?", "Warning!", JOptionPane.YES_NO_OPTION) == 0) {
            close();
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if (check1 && check2 && !txtCmndNgKhai.getText().trim().isEmpty() && !txtCmndNgMat.getText().trim().isEmpty()
                && !txtHoTenNgKhai.getText().trim().isEmpty()) {

            if (ngMat.getTinhTrang().equals("cập nhật")) {

                NhanKhauModel nk = new NhanKhauModel();
                try ( Connection connection = MysqlConnection.getMysqlConnection()) {
                    String query = "SELECT *  FROM nhankhau LEFT JOIN "
                            + "(SELECT idnhankhau, mahokhau FROM giadinh INNER JOIN hokhau ON hokhau.id = giadinh.idhokhau) AS A "
                            + "ON nhankhau.id = A.idnhankhau WHERE tinhtrang LIKE 'tạm vắng' AND cmnd LIKE '"
                            + ngMat.getCmnd() + "' ORDER by id DESC LIMIT 1";
                    try ( PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                        ResultSet rs = preparedStatement.executeQuery();

                        if (rs.next()) {
                            nk.setId(rs.getInt("id"));
                            nk.setMaHoKhau(rs.getString("mahokhau"));
                            nk.setHoTen(rs.getString("hoten"));
                            nk.setBiDanh(rs.getString("bidanh"));
                            nk.setNgaySinh(rs.getDate("ngaysinh"));
                            nk.setGioiTinh(rs.getString("gioitinh"));
                            nk.setNoiSinh(rs.getString("noisinh"));
                            nk.setNguyenQuan(rs.getString("nguyenquan"));
                            nk.setDcHienNay(rs.getString("dchiennay"));
                            nk.setDanToc(rs.getString("dantoc"));
                            nk.setTonGiao(rs.getString("tongiao"));
                            nk.setQuocTich(rs.getString("quoctich"));
                            nk.setNgheNghiep(rs.getString("nghenghiep"));
                            nk.setNoiLamViec(rs.getString("noilamviec"));
                            nk.setCmnd(rs.getString("cmnd"));
                            nk.setNgayCap(rs.getDate("ngaycap"));
                            nk.setNoiCap(rs.getString("noicap"));
                            nk.setNgayChuyenDen(rs.getDate("ngaychuyenden"));
                            nk.setNoiTruocChuyenDen(rs.getString("noitruocchuyenden"));
                            nk.setNgayChuyenDi(rs.getDate("ngaychuyendi"));
                            nk.setNoiDen(rs.getString("noiden"));
                            nk.setTinhTrang(rs.getString("tinhtrang"));
                            nk.setTuNgay(rs.getDate("tungay"));
                            nk.setDenNgay(rs.getDate("denngay"));
                            nk.setNgayLap(rs.getDate("ngaylap"));
                        }
                    }
                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                }

                if (nk.getTuNgay().getTime() < dateNgayMat.getDate().getTime()
                        && nk.getDenNgay().getTime() >= dateNgayMat.getDate().getTime()) {
                    nk.setDenNgay(new Date(dateNgayMat.getDate().getTime() - 86400000));
                    cnController.capNhatNK(nk.getId(), nk);
                } else if (nk.getTuNgay().getTime() >= dateNgayMat.getDate().getTime()) {
                    nk.setTinhTrang(null);
                    cnController.capNhatNK(nk.getId(), nk);
                }
            }
            ngMat.setTinhTrang("đã mất");
            ngMat.setNgayChuyenDi(dateNgayMat.getDate());
            ngMat.setNoiDen("đã qua đời");
            cnController.capNhatNK(ngMat.getId(), ngMat);

            HoKhau_InfoController hkInfoController = new HoKhau_InfoController();
            ThayDoiHKModel model = new ThayDoiHKModel();
            model.setMaHoKhau(ngMat.getMaHoKhau());
            model.setThongTinThayDoi("Xóa thành viên");
            model.setNoiDungThayDoi(ngMat.getHoTen() + " - " + ngMat.getCmnd());
            if (txtCmndNgKhai.getText().trim().equalsIgnoreCase("admin")) {
                model.setGhiChu("Qua đời. Khai tử bởi: admin");
            } else {
                model.setGhiChu("Qua đời. Khai tử bởi: " + txtHoTenNgKhai.getText() + " - " + txtCmndNgKhai.getText() + " - "
                        + txtSđt.getText());
            }
            hkInfoController.themThayDoiHK(model);

            if (hoKhau != null) {
                hoKhau.setTinhTrang("chuyển đi");
                hoKhau.setNgayChuyenDi(dateNgayMat.getDate());
                cnController.capNhatHK(hoKhau.getId(), hoKhau);
                
                model.setMaHoKhau(ngMat.getMaHoKhau());
                model.setThongTinThayDoi("Chuyển đi");
                model.setNoiDungThayDoi("");
                model.setGhiChu("");
                hkInfoController.themThayDoiHK(model);
            }

            JOptionPane.showMessageDialog(rootPane, "Khai tử thành công!");
            MainFrame.it.setEnabled(true);
            dispose();
        } else if (check1 || check2) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhấn nút kiểm tra!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (txtCmndNgKhai.getText().trim().isEmpty() || txtCmndNgMat.getText().trim().isEmpty()
                || txtHoTenNgKhai.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền vào các trường trên!", "Warning!", JOptionPane.WARNING_MESSAGE);
            check1 = false;
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnKiemTraNgKhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraNgKhaiActionPerformed
        if (txtCmndNgKhai.getText().trim().length() != 8
                && !(txtCmndNgKhai.getText().trim().length() == 5 && txtCmndNgKhai.getText().trim().equals("admin"))
                && txtCmndNgKhai.getText().trim().length() != 9
                && txtCmndNgKhai.getText().trim().length() != 12) {
            check1 = false;
            JOptionPane.showMessageDialog(rootPane, "Định dạng số CMT/CCCD không hợp lệ!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (txtCmndNgMat.getText().trim().equals(txtCmndNgKhai.getText().trim())) {
            JOptionPane.showMessageDialog(rootPane, "Số CMT/CCCD của người khai và người mất phải khác nhau!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            if (ktController.checkCmndSs_Cn(txtCmndNgKhai.getText().trim())) {
                if ("admin".equals(txtCmndNgKhai.getText().trim())) {
                    txtHoTenNgKhai.setText("admin");
                    txtSđt.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Kiểm tra thành công!");
                    check1 = true;
                } else {
                    if (!txtHoTenNgKhai.getText().trim().isEmpty() && !txtSđt.getText().trim().isEmpty()) {
                        check1 = true;
                        if (txtSđt.getText().trim().length() != 10) {
                            check1 = false;
                            JOptionPane.showMessageDialog(rootPane, "Định dạng số điện thoại không hợp lệ!", "Warning!", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Số CMT/CCCD chưa có trong hệ thống! Vui lòng nhập họ tên "
                                + "và số điện thoại liên lạc!", "Warning!", JOptionPane.WARNING_MESSAGE);
                    }
                    if (check1) {
                        JOptionPane.showMessageDialog(rootPane, "Kiểm tra thành công!");
                    }
                }
            } else {
                check1 = true;
                JOptionPane.showMessageDialog(rootPane, "Kiểm tra thành công!");

                ngKhai = ktController.findByCondition(txtCmndNgKhai.getText().trim()).get(0);
                txtHoTenNgKhai.setText(ngKhai.getHoTen());
                txtSđt.setText("");
            }
        }
    }//GEN-LAST:event_btnKiemTraNgKhaiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKiemTraNgKhai;
    private javax.swing.JButton btnKiemTraNgMat;
    private javax.swing.JButton btnXacNhan;
    private com.toedter.calendar.JDateChooser dateNgayMat;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCmndNgKhai;
    private javax.swing.JTextField txtCmndNgMat;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTenNgKhai;
    private javax.swing.JTextField txtHoTenNgMat;
    private javax.swing.JTextField txtNoiThuongTru;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSđt;
    // End of variables declaration//GEN-END:variables
}
